<?php

namespace App\Livewire;

use Livewire\Component;
use Filament\Notifications\Livewire\DatabaseNotifications as BaseDatabaseNotifications;


class DatabaseNotifications extends BaseDatabaseNotifications
{
    public function __construct()
    {
        dd('asdasd');
    }
    public function skipMount()
    {
        dd('asdasd');
        parent::skipMount(); // TODO: Change the autogenerated stub
    }
//    public function render()
//    {
//        return view('livewire.database-notifications');
//    }
}
