name: Build and deploy

on:
  push:
    branches: ['main']

jobs:
  push_to_registry:
    name: Push Docker image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.menuma.online
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: danielsoheil/menuma-backend

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: registry.menuma.online/menuma/backend-laravel-production:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Call API to update server
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ secrets.SERVER_UPDATE_URL }}
          accept: 200
          #          headers:  '{ "Authorization": "Bearer mytoken" }'
          headers: ${{ secrets.SERVER_UPDATE_HEADER }}
          timeout: 10000
          retries: 3
